### PR TITLE
Extract configurations to provide flexibility for tuning

### PR DESCRIPTION
**Pull request by Jeffwan**
*Issue #, if available:* 
#6 

*Description of changes:*
Extract configurations to provide flexibility

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yongwww** [comment]
lgtm

**Review by yongwww — COMMENTED** [review]
lgtm, could you also share your best performing values of these parameters?

**Comment by Jeffwan** [comment]
@yongwww 
I tried several combinations but didn't see obvious performance lift. 
I am using p3.16xlarge and it comes with 2 physical cpus, each one has 16 cores, according to hyper threading, we get 64 cores in total. 

Based on this, I just use 
- inter_op_parallelism_threads - 8
- intra_op_parallelism_threads - 2
- num_parallel_calls - 8

Based on Tensorflow performance guidance, 
should set `intra_op_parallelism_threads ` equal to the number of physical cores which is 2,
should set `inter_op_parallelism_threads ` equal to the number of sockets which is also 2.

Do you have any insights?

**Comment by yongwww** [comment]
@Jeffwan  tried to tune with these parameters with mkl enabled, it helped. Haven't tried to tune it with vanilla tf.

**Comment by Jeffwan** [comment]
@yongwww Right, I use vanilla tf and I will have a try with mkl tf. Thanks!

**Pull request merged**
